-- =========================================================
-- HOSPITAL MANAGEMENT SYSTEM
-- SQL ANALYSIS PROJECT
-- =========================================================

#====Total Visits  #
SELECT COUNT(*) AS TOTAL_VISITS
FROM VISITS;

2. Total Patients
SELECT COUNT(DISTINCT PATIENT_ID) AS TOTAL_PATIENTS
FROM VISITS;

3. Total Doctors
SELECT COUNT(DISTINCT DOCTOR_ID) AS TOTAL_DOCTORS
FROM VISITS;

4. Total Revenue
SELECT SUM(REVENUE) AS TOTAL_REVENUE
FROM VISITS;

5. Average Revenue per Visit
SELECT AVG(REVENUE) AS AVG_REVENUE_PER_VISIT
FROM VISITS;

6. Average Stay Days
SELECT AVG(STAY_DAYS) AS AVG_STAY_DAYS
FROM VISITS;

7. Average Revenue per Patient
SELECT
    SUM(REVENUE) / COUNT(DISTINCT PATIENT_ID)
        AS AVG_REVENUE_PER_PATIENT
FROM VISITS;

8. Average Patients per Doctor
SELECT
    COUNT(DISTINCT PATIENT_ID) * 1.0
    / COUNT(DISTINCT DOCTOR_ID) AS AVG_PATIENTS_PER_DOCTOR
FROM VISITS;

9. Revenue by Department
SELECT
    DEP.DEPARTMENT_NAME,
    SUM(V.REVENUE) AS TOTAL_REVENUE
FROM VISITS AS V
INNER JOIN DOCTORS AS D
    ON D.DOCTOR_ID = V.DOCTOR_ID
INNER JOIN DEPARTMENTS AS DEP
    ON DEP.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY DEP.DEPARTMENT_NAME
ORDER BY TOTAL_REVENUE DESC;

10. Revenue by Payment Mode
SELECT
    PAYMENT_MODE,
    SUM(REVENUE) AS TOTAL_REVENUE
FROM VISITS
GROUP BY PAYMENT_MODE
ORDER BY TOTAL_REVENUE DESC;

11. Visits by Admission Type
SELECT
    ADMISSION_TYPE,
    COUNT(*) AS TOTAL_VISITS
FROM VISITS
GROUP BY ADMISSION_TYPE
ORDER BY TOTAL_VISITS DESC;

12. Average Stay Days by Admission Type

SELECT
    ADMISSION_TYPE,
    AVG(STAY_DAYS) AS AVG_STAY_DAYS
FROM VISITS
GROUP BY ADMISSION_TYPE;